package com.coffee_shop.Views;

/**
 *
 * @author kiwog
 */

import java.util.ArrayList; 

import javax.swing.Icon;
import javax.swing.ImageIcon;

import com.coffee_shop.Models.OrderModel;
import com.coffee_shop.Handlers.ProductRedirect;
import com.coffee_shop.Repositories.OrderRepository;
import com.coffee_shop.Utilities.PriceFormatParsing;

public class CartPage extends javax.swing.JFrame {

    /**
     * Creates new form CartPage
     */

    private int TotalPrice;
    private String[] TableModel;
    private ArrayList<OrderModel> Orders;
    private PriceFormatParsing PriceFormat;

    private String ProductNameEdit;
    private int ProductPriceEdit;
    private String ProductImageEdit;
    private int ProductQuantityEdit;

    private OrderRepository RepoOrders;

    public CartPage() {

        this.RepoOrders = new OrderRepository();
        this.PriceFormat = new PriceFormatParsing();

        this.TotalPrice = 0;
        this.Orders = this.RepoOrders.showOrders();
        this.TableModel = new String[] {"", "", "", ""};

        this.ProductNameEdit  = "";
        this.ProductPriceEdit = 0;
        this.ProductImageEdit = "";
        this.ProductQuantityEdit = 0;

        initComponents(this.Orders.size());

        TableComponents();
        
        TotalOrderShow.setText("Total Harga : " + 
            this.PriceFormat.PriceNumberToPriceStringFormat(this.TotalPrice)
        );
    }

    private void TableComponents() {

        String ImageLocation = "C:\\Users\\kiwog\\Documents\\projects\\application projects\\coffee_shop\\design\\drinks\\";
      
        ProductTable.setRowHeight(100);

        for (int IndexOrderRepo = 0; IndexOrderRepo < Orders.size(); IndexOrderRepo ++) {

            // product image record 
            ProductTable.setValueAt(new ImageIcon(ImageLocation + Orders.get(IndexOrderRepo).getProductImage()),
                IndexOrderRepo, 0);
            
            // product name record
            ProductTable.setValueAt(Orders.get(IndexOrderRepo).getProduct(), IndexOrderRepo, 1);

            // product price record
            ProductTable.setValueAt(
                this.PriceFormat.PriceNumberToPriceStringFormat(Orders.get(IndexOrderRepo).getPrice()),
                IndexOrderRepo, 2);

            // product quantity record
            ProductTable.setValueAt(String.valueOf(Orders.get(IndexOrderRepo).getQuantity()), IndexOrderRepo, 3);

            this.TotalPrice += (
                Orders.get(IndexOrderRepo).getPrice() *
                Orders.get(IndexOrderRepo).getQuantity()
            );
            
        }

        EditButton.setVisible(false);
        DeleteButton.setVisible(false);

    }

    private Object[][] TableStructures (int TableSize) {

        int TableRecord = this.TableModel.length;

        if (TableSize <= 3) {TableSize = 4;}

        Object[][] Structure = new Object[TableSize][TableRecord];

        for (int IndexField = 0; IndexField < TableSize; IndexField++) {

            for (int IndexRecord = 0; IndexRecord < TableRecord; IndexRecord++) {

                Structure[IndexField][IndexRecord] = null;

            }

        }

        return Structure;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents(int TableSize) {

        jPanel1 = new javax.swing.JPanel();
        SettingIcon = new javax.swing.JLabel();
        UserIcon = new javax.swing.JLabel();
        CartIcon = new javax.swing.JLabel();
        BackIcon = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ProductTable = new javax.swing.JTable(){
            public Class getColumnClass(int column) {
                return (column == 0) ? Icon.class : Object.class;
            }
        };
        OrderHeaderText = new javax.swing.JLabel();
        TotalOrderShow = new javax.swing.JLabel();
        EditButton = new javax.swing.JLabel();
        DeleteButton = new javax.swing.JLabel();
        BuyNowButton = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });

        SettingIcon.setIcon(new javax.swing.ImageIcon("C:\\Users\\kiwog\\Documents\\projects\\application projects\\coffee_shop\\design\\icons\\setting.png")); // NOI18N

        UserIcon.setIcon(new javax.swing.ImageIcon("C:\\Users\\kiwog\\Documents\\projects\\application projects\\coffee_shop\\design\\icons\\user.png")); // NOI18N

        CartIcon.setIcon(new javax.swing.ImageIcon("C:\\Users\\kiwog\\Documents\\projects\\application projects\\coffee_shop\\design\\icons\\cart.png")); // NOI18N
        CartIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CartIconMouseClicked(evt);
            }
        });

        BackIcon.setIcon(new javax.swing.ImageIcon("C:\\Users\\kiwog\\Documents\\projects\\application projects\\coffee_shop\\design\\icons\\back.png")); // NOI18N
        BackIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackIconMouseClicked(evt);
            }
        });

        ProductTable.setBackground(new java.awt.Color(0, 0, 0));
        ProductTable.setFont(new java.awt.Font("Ubuntu Light", 1, 24)); // NOI18N
        ProductTable.setForeground(new java.awt.Color(255, 255, 255));
        ProductTable.setModel(new javax.swing.table.DefaultTableModel(
            TableStructures (TableSize),
            this.TableModel
        )); 
        ProductTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProductTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ProductTable);

        OrderHeaderText.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        OrderHeaderText.setForeground(new java.awt.Color(255, 255, 255));
        OrderHeaderText.setText("Pesanan Anda");

        TotalOrderShow.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        TotalOrderShow.setForeground(new java.awt.Color(255, 255, 255));
        TotalOrderShow.setText("<TotalOrderShow>");

        EditButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\kiwog\\Documents\\projects\\application projects\\coffee_shop\\design\\icons\\edit.png")); // NOI18N
        EditButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EditButtonMouseClicked(evt);
            }
        });

        DeleteButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\kiwog\\Documents\\projects\\application projects\\coffee_shop\\design\\icons\\delete.png")); // NOI18N
        DeleteButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DeleteButtonMouseClicked(evt);
            }
        });

        BuyNowButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\kiwog\\Documents\\projects\\application projects\\coffee_shop\\design\\icons\\buy_now.png")); // NOI18N
        BuyNowButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BuyNowButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(BackIcon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 721, Short.MAX_VALUE)
                .addComponent(CartIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(UserIcon)
                .addGap(18, 18, 18)
                .addComponent(SettingIcon)
                .addGap(58, 58, 58))
            .addComponent(jScrollPane1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(OrderHeaderText)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(TotalOrderShow)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(DeleteButton)
                .addGap(18, 18, 18)
                .addComponent(EditButton)
                .addGap(18, 18, 18)
                .addComponent(BuyNowButton)
                .addGap(40, 40, 40))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(SettingIcon, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CartIcon, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(UserIcon, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(BackIcon)))
                .addGap(35, 35, 35)
                .addComponent(OrderHeaderText)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(TotalOrderShow)
                        .addContainerGap(215, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EditButton)
                            .addComponent(BuyNowButton)
                            .addComponent(DeleteButton))
                        .addGap(205, 205, 205))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CartIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CartIconMouseClicked
        // TODO add your handling code here:
        System.out.println("Cart Icon");
    }//GEN-LAST:event_CartIconMouseClicked

    private void BackIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackIconMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);

        ProductPage productPage = new ProductPage();
        productPage.setVisible(true);
        productPage.pack();
        productPage.setLocationRelativeTo(null);
        productPage.setDefaultCloseOperation(ProductPage.EXIT_ON_CLOSE);
    }//GEN-LAST:event_BackIconMouseClicked

    private void EditButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditButtonMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        
        new ProductRedirect(this.ProductNameEdit, this.ProductPriceEdit, 
            this.ProductImageEdit, this.ProductQuantityEdit, "edit");
        
    }//GEN-LAST:event_EditButtonMouseClicked

    private void BuyNowButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BuyNowButtonMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);

        ShippingPage shippingPage = new ShippingPage();
        shippingPage.setVisible(true);
        shippingPage.pack();
        shippingPage.setLocationRelativeTo(null);
        shippingPage.setDefaultCloseOperation(ShippingPage.EXIT_ON_CLOSE);
    }//GEN-LAST:event_BuyNowButtonMouseClicked

    private void DeleteButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteButtonMouseClicked
        // TODO add your handling code here:
        this.RepoOrders.deleteOrder(ProductNameEdit);
        this.setVisible(false);
        
        CartPage cartPage = new CartPage();
        cartPage.setVisible(true);
        cartPage.pack();
        cartPage.setLocationRelativeTo(null);
        cartPage.setDefaultCloseOperation(CartPage.EXIT_ON_CLOSE);

    }//GEN-LAST:event_DeleteButtonMouseClicked

    private void ProductTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProductTableMouseClicked
        // TODO add your handling code here:

        int IndexField = ProductTable.getSelectedRow();
        
        this.ProductNameEdit  = Orders.get(IndexField).getProduct();
        this.ProductPriceEdit = Orders.get(IndexField).getPrice();
        this.ProductImageEdit = Orders.get(IndexField).getProductImage();
        this.ProductQuantityEdit = Orders.get(IndexField).getQuantity();

        EditButton.setVisible(true);
        DeleteButton.setVisible(true);


    }//GEN-LAST:event_ProductTableMouseClicked

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        // TODO add your handling code here:

        EditButton.setVisible(false);
        DeleteButton.setVisible(false);

    }//GEN-LAST:event_jPanel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CartPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CartPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CartPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CartPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CartPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackIcon;
    private javax.swing.JLabel BuyNowButton;
    private javax.swing.JLabel CartIcon;
    private javax.swing.JLabel DeleteButton;
    private javax.swing.JLabel EditButton;
    private javax.swing.JLabel OrderHeaderText;
    private javax.swing.JTable ProductTable;
    private javax.swing.JLabel SettingIcon;
    private javax.swing.JLabel TotalOrderShow;
    private javax.swing.JLabel UserIcon;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
