package com.coffee_shop.Views;

/**
 *
 * @author kiwog
 */

// import com.coffee_shop.Views.CartPage;
import com.coffee_shop.Utilities.SayHayOfDate;
import com.coffee_shop.Handlers.ProductRedirect;

public class ProductPage extends javax.swing.JFrame {

    /**
     * Creates new form ProductPage
     */
    public ProductPage() {
        
        initComponents();
        
        this.setTitle("Produk");
        this.setVisible(true);

        UserSayHay.setText("Selamat "+ new SayHayOfDate().getSayHay() +", Qywok");
        UserQuestion.setText("Ingin Minum Apa "+ new SayHayOfDate().getSayHay() +" Ini ?.");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ProductPanel = new javax.swing.JPanel();
        CartIcon = new javax.swing.JLabel();
        UserIcon = new javax.swing.JLabel();
        SettingIcon = new javax.swing.JLabel();
        Header = new javax.swing.JLabel();
        UserDiscount = new javax.swing.JLabel();
        UserQuestion = new javax.swing.JLabel();
        SearchMenu = new javax.swing.JLabel();
        UserSayHay = new javax.swing.JLabel();
        AffogatoImage = new javax.swing.JLabel();
        AffogatoName = new javax.swing.JLabel();
        PicolloImage = new javax.swing.JLabel();
        PicolloName = new javax.swing.JLabel();
        MatchaImage = new javax.swing.JLabel();
        MatchaName = new javax.swing.JLabel();
        AmericanoName = new javax.swing.JLabel();
        AmericanoImage = new javax.swing.JLabel();
        TaroImage = new javax.swing.JLabel();
        TaroName = new javax.swing.JLabel();
        ChocoImage = new javax.swing.JLabel();
        ChocoName = new javax.swing.JLabel();
        HazelnutImage = new javax.swing.JLabel();
        HazelnutName = new javax.swing.JLabel();
        LatteImage = new javax.swing.JLabel();
        LatteName = new javax.swing.JLabel();
        LycheeImage = new javax.swing.JLabel();
        LycheeName = new javax.swing.JLabel();
        LemonTeaName = new javax.swing.JLabel();
        LemonTeaImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 102, 0));

        ProductPanel.setBackground(new java.awt.Color(0, 0, 0));

        CartIcon.setIcon(new javax.swing.ImageIcon("C:\\Users\\kiwog\\Documents\\projects\\application projects\\coffee_shop\\design\\icons\\cart.png")); // NOI18N
        CartIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CartIconMouseClicked(evt);
            }
        });

        UserIcon.setIcon(new javax.swing.ImageIcon("C:\\Users\\kiwog\\Documents\\projects\\application projects\\coffee_shop\\design\\icons\\user.png")); // NOI18N

        SettingIcon.setIcon(new javax.swing.ImageIcon("C:\\Users\\kiwog\\Documents\\projects\\application projects\\coffee_shop\\design\\icons\\setting.png")); // NOI18N

        Header.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        Header.setForeground(new java.awt.Color(255, 255, 255));
        Header.setText("Coffee And Eatry");

        UserDiscount.setFont(new java.awt.Font("Ubuntu Medium", 0, 18)); // NOI18N
        UserDiscount.setForeground(new java.awt.Color(255, 255, 255));
        UserDiscount.setText("30% OFF TAKE AWAY AT GEDUNG A & B");

        UserQuestion.setFont(new java.awt.Font("Ubuntu", 1, 20)); // NOI18N
        UserQuestion.setForeground(new java.awt.Color(255, 255, 255));

        SearchMenu.setFont(new java.awt.Font("Ubuntu Medium", 0, 16)); // NOI18N
        SearchMenu.setForeground(new java.awt.Color(255, 255, 255));
        SearchMenu.setIcon(new javax.swing.ImageIcon("C:\\Users\\kiwog\\Documents\\projects\\application projects\\coffee_shop\\design\\icons\\search.png")); // NOI18N
        SearchMenu.setText(" Cari Menu");

        UserSayHay.setFont(new java.awt.Font("Ubuntu Medium", 0, 18)); // NOI18N
        UserSayHay.setForeground(new java.awt.Color(255, 255, 255));

        AffogatoImage.setIcon(new javax.swing.ImageIcon("C:\\Users\\kiwog\\Documents\\projects\\application projects\\coffee_shop\\design\\drinks\\affogato.jpg")); // NOI18N
        AffogatoImage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AffogatoImageMouseClicked(evt);
            }
        });

        AffogatoName.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        AffogatoName.setForeground(new java.awt.Color(255, 255, 255));
        AffogatoName.setText("Affogato");
        AffogatoName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AffogatoNameMouseClicked(evt);
            }
        });

        PicolloImage.setIcon(new javax.swing.ImageIcon("C:\\Users\\kiwog\\Documents\\projects\\application projects\\coffee_shop\\design\\drinks\\picolo.jpg")); // NOI18N
        PicolloImage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PicolloImageMouseClicked(evt);
            }
        });

        PicolloName.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        PicolloName.setForeground(new java.awt.Color(255, 255, 255));
        PicolloName.setText("Picollo");
        PicolloName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PicolloNameMouseClicked(evt);
            }
        });

        MatchaImage.setIcon(new javax.swing.ImageIcon("C:\\Users\\kiwog\\Documents\\projects\\application projects\\coffee_shop\\design\\drinks\\matcha.jpg")); // NOI18N
        MatchaImage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MatchaImageMouseClicked(evt);
            }
        });

        MatchaName.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        MatchaName.setForeground(new java.awt.Color(255, 255, 255));
        MatchaName.setText("Matcha");
        MatchaName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MatchaNameMouseClicked(evt);
            }
        });

        AmericanoName.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        AmericanoName.setForeground(new java.awt.Color(255, 255, 255));
        AmericanoName.setText("Americano");
        AmericanoName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AmericanoNameMouseClicked(evt);
            }
        });

        AmericanoImage.setIcon(new javax.swing.ImageIcon("C:\\Users\\kiwog\\Documents\\projects\\application projects\\coffee_shop\\design\\drinks\\americano.jpg")); // NOI18N
        AmericanoImage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AmericanoImageMouseClicked(evt);
            }
        });

        TaroImage.setIcon(new javax.swing.ImageIcon("C:\\Users\\kiwog\\Documents\\projects\\application projects\\coffee_shop\\design\\drinks\\taro.jpg")); // NOI18N
        TaroImage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TaroImageMouseClicked(evt);
            }
        });

        TaroName.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        TaroName.setForeground(new java.awt.Color(255, 255, 255));
        TaroName.setText("Taro");
        TaroName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TaroNameMouseClicked(evt);
            }
        });

        ChocoImage.setIcon(new javax.swing.ImageIcon("C:\\Users\\kiwog\\Documents\\projects\\application projects\\coffee_shop\\design\\drinks\\choco.jpg")); // NOI18N
        ChocoImage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ChocoImageMouseClicked(evt);
            }
        });

        ChocoName.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        ChocoName.setForeground(new java.awt.Color(255, 255, 255));
        ChocoName.setText("Choco");
        ChocoName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ChocoNameMouseClicked(evt);
            }
        });

        HazelnutImage.setIcon(new javax.swing.ImageIcon("C:\\Users\\kiwog\\Documents\\projects\\application projects\\coffee_shop\\design\\drinks\\hazelnut.jpg")); // NOI18N
        HazelnutImage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HazelnutImageMouseClicked(evt);
            }
        });

        HazelnutName.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        HazelnutName.setForeground(new java.awt.Color(255, 255, 255));
        HazelnutName.setText("Hazelnut");
        HazelnutName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HazelnutNameMouseClicked(evt);
            }
        });

        LatteImage.setIcon(new javax.swing.ImageIcon("C:\\Users\\kiwog\\Documents\\projects\\application projects\\coffee_shop\\design\\drinks\\latte.jpg")); // NOI18N
        LatteImage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LatteImageMouseClicked(evt);
            }
        });

        LatteName.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        LatteName.setForeground(new java.awt.Color(255, 255, 255));
        LatteName.setText("Latte");
        LatteName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LatteNameMouseClicked(evt);
            }
        });

        LycheeImage.setIcon(new javax.swing.ImageIcon("C:\\Users\\kiwog\\Documents\\projects\\application projects\\coffee_shop\\design\\drinks\\lychee.jpg")); // NOI18N
        LycheeImage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LycheeImageMouseClicked(evt);
            }
        });

        LycheeName.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        LycheeName.setForeground(new java.awt.Color(255, 255, 255));
        LycheeName.setText("Lychee");
        LycheeName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LycheeNameMouseClicked(evt);
            }
        });

        LemonTeaName.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        LemonTeaName.setForeground(new java.awt.Color(255, 255, 255));
        LemonTeaName.setText("Lemon Tea");
        LemonTeaName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LemonTeaNameMouseClicked(evt);
            }
        });

        LemonTeaImage.setIcon(new javax.swing.ImageIcon("C:\\Users\\kiwog\\Documents\\projects\\application projects\\coffee_shop\\design\\drinks\\lemon.jpg")); // NOI18N
        LemonTeaImage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LemonTeaImageMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout ProductPanelLayout = new javax.swing.GroupLayout(ProductPanel);
        ProductPanel.setLayout(ProductPanelLayout);
        ProductPanelLayout.setHorizontalGroup(
            ProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProductPanelLayout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addGroup(ProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ProductPanelLayout.createSequentialGroup()
                        .addComponent(Header)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CartIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(UserIcon)
                        .addGap(18, 18, 18)
                        .addComponent(SettingIcon))
                    .addGroup(ProductPanelLayout.createSequentialGroup()
                        .addGroup(ProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(UserSayHay)
                            .addComponent(UserDiscount)
                            .addComponent(UserQuestion)
                            .addComponent(SearchMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(ProductPanelLayout.createSequentialGroup()
                                .addGroup(ProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(PicolloImage)
                                    .addComponent(AffogatoImage)
                                    .addGroup(ProductPanelLayout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addGroup(ProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(AffogatoName)
                                            .addGroup(ProductPanelLayout.createSequentialGroup()
                                                .addGap(7, 7, 7)
                                                .addComponent(PicolloName)))))
                                .addGroup(ProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(ProductPanelLayout.createSequentialGroup()
                                        .addGap(68, 68, 68)
                                        .addGroup(ProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(MatchaImage)
                                            .addComponent(AmericanoImage)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProductPanelLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(ProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProductPanelLayout.createSequentialGroup()
                                                .addComponent(AmericanoName)
                                                .addGap(13, 13, 13))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProductPanelLayout.createSequentialGroup()
                                                .addComponent(MatchaName)
                                                .addGap(23, 23, 23)))))))
                        .addGroup(ProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ProductPanelLayout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(ProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TaroImage)
                                    .addComponent(ChocoImage)
                                    .addGroup(ProductPanelLayout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addComponent(ChocoName)))
                                .addGap(66, 66, 66))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProductPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TaroName)
                                .addGap(99, 99, 99)))
                        .addGroup(ProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LycheeImage)
                            .addComponent(HazelnutImage)
                            .addGroup(ProductPanelLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(HazelnutName))
                            .addGroup(ProductPanelLayout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(LycheeName)))
                        .addGroup(ProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ProductPanelLayout.createSequentialGroup()
                                .addGap(84, 84, 84)
                                .addComponent(LemonTeaName))
                            .addGroup(ProductPanelLayout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addGroup(ProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LemonTeaImage)
                                    .addComponent(LatteImage)
                                    .addGroup(ProductPanelLayout.createSequentialGroup()
                                        .addGap(32, 32, 32)
                                        .addComponent(LatteName)))))
                        .addGap(0, 65, Short.MAX_VALUE)))
                .addGap(58, 58, 58))
        );
        ProductPanelLayout.setVerticalGroup(
            ProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProductPanelLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(ProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Header)
                    .addGroup(ProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(SettingIcon, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CartIcon, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(UserIcon, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(37, 37, 37)
                .addComponent(UserSayHay)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(UserQuestion)
                .addGap(26, 26, 26)
                .addComponent(UserDiscount)
                .addGap(43, 43, 43)
                .addComponent(SearchMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(28, 28, 28)
                .addGroup(ProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ProductPanelLayout.createSequentialGroup()
                        .addComponent(AffogatoImage)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(AffogatoName)
                        .addGap(66, 66, 66)
                        .addComponent(PicolloImage)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(PicolloName))
                    .addGroup(ProductPanelLayout.createSequentialGroup()
                        .addComponent(AmericanoImage)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(AmericanoName)
                        .addGap(66, 66, 66)
                        .addComponent(MatchaImage)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(MatchaName))
                    .addGroup(ProductPanelLayout.createSequentialGroup()
                        .addComponent(ChocoImage)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ChocoName)
                        .addGap(66, 66, 66)
                        .addComponent(TaroImage)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TaroName))
                    .addGroup(ProductPanelLayout.createSequentialGroup()
                        .addComponent(HazelnutImage)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(HazelnutName)
                        .addGap(66, 66, 66)
                        .addComponent(LycheeImage)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LycheeName))
                    .addGroup(ProductPanelLayout.createSequentialGroup()
                        .addComponent(LatteImage)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LatteName)
                        .addGap(66, 66, 66)
                        .addComponent(LemonTeaImage)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LemonTeaName)))
                .addGap(155, 155, 155))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ProductPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ProductPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 
    
    // cart icon
    private void CartIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CartIconMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        
        CartPage cartPage = new CartPage();
        cartPage.setVisible(true);
        cartPage.pack();
        cartPage.setLocationRelativeTo(null);
        cartPage.setDefaultCloseOperation(CartPage.EXIT_ON_CLOSE);
    }//GEN-LAST:event_CartIconMouseClicked

    
    
    /* Affogato Product */
    private void AffogatoImageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AffogatoImageMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new ProductRedirect("Affogato", 10000, "affogato.jpg", 1, "normal");
    }//GEN-LAST:event_AffogatoImageMouseClicked

    private void AffogatoNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AffogatoNameMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new ProductRedirect("Affogato", 10000, "affogato.jpg", 1, "normal");
    }//GEN-LAST:event_AffogatoNameMouseClicked

    private void AmericanoImageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AmericanoImageMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new ProductRedirect("Americano", 10000, "americano.jpg", 1, "normal");
    }//GEN-LAST:event_AmericanoImageMouseClicked

    private void AmericanoNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AmericanoNameMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new ProductRedirect("Americano", 10000, "americano.jpg", 1, "normal");
    }//GEN-LAST:event_AmericanoNameMouseClicked

    private void ChocoImageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChocoImageMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new ProductRedirect("Choco", 10000, "choco.jpg", 1, "normal");
    }//GEN-LAST:event_ChocoImageMouseClicked

    private void ChocoNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChocoNameMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new ProductRedirect("Choco", 10000, "choco.jpg", 1, "normal");
    }//GEN-LAST:event_ChocoNameMouseClicked

    private void HazelnutImageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HazelnutImageMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new ProductRedirect("Hazelnut", 10000, "hazelnut.jpg", 1, "normal");
    }//GEN-LAST:event_HazelnutImageMouseClicked

    private void HazelnutNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HazelnutNameMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new ProductRedirect("Hazelnut", 10000, "hazelnut.jpg", 1, "normal");
    }//GEN-LAST:event_HazelnutNameMouseClicked

    private void LatteImageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LatteImageMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new ProductRedirect("Latte", 10000, "latte.jpg", 1, "normal");
    }//GEN-LAST:event_LatteImageMouseClicked

    private void LatteNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LatteNameMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new ProductRedirect("Latte", 10000, "latte.jpg", 1, "normal");
    }//GEN-LAST:event_LatteNameMouseClicked

    private void PicolloImageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PicolloImageMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new ProductRedirect("Picollo", 10000, "picolo.jpg", 1, "normal");
    }//GEN-LAST:event_PicolloImageMouseClicked

    private void PicolloNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PicolloNameMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new ProductRedirect("Picollo", 10000, "picolo.jpg", 1, "normal");
    }//GEN-LAST:event_PicolloNameMouseClicked

    private void MatchaImageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MatchaImageMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new ProductRedirect("Matcha", 10000, "matcha.jpg", 1, "normal");
    }//GEN-LAST:event_MatchaImageMouseClicked

    private void MatchaNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MatchaNameMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new ProductRedirect("Matcha", 10000, "matcha.jpg", 1, "normal");
    }//GEN-LAST:event_MatchaNameMouseClicked

    private void TaroImageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TaroImageMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new ProductRedirect("Taro", 10000, "taro.jpg", 1, "normal");
    }//GEN-LAST:event_TaroImageMouseClicked

    private void TaroNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TaroNameMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new ProductRedirect("Taro", 10000, "taro.jpg", 1, "normal");
    }//GEN-LAST:event_TaroNameMouseClicked

    private void LycheeImageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LycheeImageMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new ProductRedirect("Lychee", 10000, "lychee.jpg", 1, "normal");
    }//GEN-LAST:event_LycheeImageMouseClicked

    private void LycheeNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LycheeNameMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new ProductRedirect("Lychee", 10000, "lychee.jpg", 1, "normal");
    }//GEN-LAST:event_LycheeNameMouseClicked

    private void LemonTeaImageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LemonTeaImageMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new ProductRedirect("Lemon Tea", 10000, "lemon.jpg", 1, "normal");
    }//GEN-LAST:event_LemonTeaImageMouseClicked

    private void LemonTeaNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LemonTeaNameMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new ProductRedirect("Lemon Tea", 10000, "lemon.jpg", 1, "normal");
    }//GEN-LAST:event_LemonTeaNameMouseClicked

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ProductPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ProductPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ProductPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ProductPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ProductPage().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AffogatoImage;
    private javax.swing.JLabel AffogatoName;
    private javax.swing.JLabel AmericanoImage;
    private javax.swing.JLabel AmericanoName;
    private javax.swing.JLabel CartIcon;
    private javax.swing.JLabel ChocoImage;
    private javax.swing.JLabel ChocoName;
    private javax.swing.JLabel HazelnutImage;
    private javax.swing.JLabel HazelnutName;
    private javax.swing.JLabel Header;
    private javax.swing.JLabel LatteImage;
    private javax.swing.JLabel LatteName;
    private javax.swing.JLabel LemonTeaImage;
    private javax.swing.JLabel LemonTeaName;
    private javax.swing.JLabel LycheeImage;
    private javax.swing.JLabel LycheeName;
    private javax.swing.JLabel MatchaImage;
    private javax.swing.JLabel MatchaName;
    private javax.swing.JLabel PicolloImage;
    private javax.swing.JLabel PicolloName;
    private javax.swing.JPanel ProductPanel;
    private javax.swing.JLabel SearchMenu;
    private javax.swing.JLabel SettingIcon;
    private javax.swing.JLabel TaroImage;
    private javax.swing.JLabel TaroName;
    private javax.swing.JLabel UserDiscount;
    private javax.swing.JLabel UserIcon;
    private javax.swing.JLabel UserQuestion;
    private javax.swing.JLabel UserSayHay;
    // End of variables declaration//GEN-END:variables
}
