/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.coffee_shop.Views;

/**
 *
 * @author kiwog
 */
import javax.swing.ImageIcon;
// import com.coffee_shop.Views.ProductPage;
import com.coffee_shop.Models.OrderModel;
import com.coffee_shop.Utilities.PriceFormatParsing;
import com.coffee_shop.Repositories.OrderRepository;
import com.coffee_shop.Configurations.EnvironmentVariableConfiguration;


public class ProductOrderPage extends javax.swing.JFrame {

    /**
     * Creates new form ProductOrderPage
     */
    
    private final String ProductName;
    private final int ProductPrice;
    private final String ProductImageDetail;
    private final int ProductStock;
    
    private int ProductStockDefault;
    private int QuantityProductDefault;
    private int MinimumOrder;

    private String BackFormat;
    
    private final PriceFormatParsing PriceParsing;
    
    public ProductOrderPage(String ProductName, int ProductPrice,
        String ProductImageDetail, int QuantityProductDefault, String BackFormat) {
        
        initComponents();

        EnvironmentVariableConfiguration VariableEnv = new EnvironmentVariableConfiguration();
        
        this.ProductName   = ProductName;
        this.ProductPrice  = ProductPrice;
        this.ProductImageDetail = ProductImageDetail;

        this.BackFormat = BackFormat;

        this.ProductStock  = Integer.parseInt(VariableEnv.Environment.getProperty("MAX_ORDERS"));
        this.MinimumOrder = Integer.parseInt(VariableEnv.Environment.getProperty("MIN_ORDERS"));
        
        this.QuantityProductDefault = QuantityProductDefault;
        this.ProductStockDefault = this.ProductStock - 1;
        
        this.PriceParsing = new PriceFormatParsing();
        
        String ImagePath = "C:\\Users\\kiwog\\Documents\\projects\\application projects\\coffee_shop\\design\\drinks_big\\";
        
        this.setTitle(this.ProductName);
        this.setVisible(true);
        ProductImage.setIcon(new ImageIcon(ImagePath + this.ProductImageDetail));
        ProductImage.setText("");
        
        ProductShowName.setText(this.ProductName);
        ProductShowPrice.setText(this.PriceParsing.PriceNumberToPriceStringFormat(this.ProductPrice));
        ProductShowStock.setText(String.valueOf(this.ProductStockDefault));
        ProductShowQuantity.setText(String.valueOf(this.QuantityProductDefault));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BackIcon = new javax.swing.JLabel();
        ProductImage = new javax.swing.JLabel();
        ProductShowName = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        QuantityIncrase = new javax.swing.JLabel();
        Quantitydecrase = new javax.swing.JLabel();
        ProductShowQuantity = new javax.swing.JLabel();
        AddToCart = new javax.swing.JLabel();
        ProductShowPrice = new javax.swing.JLabel();
        StockTitle = new javax.swing.JLabel();
        ProductShowStock = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        BackIcon.setIcon(new javax.swing.ImageIcon("C:\\Users\\kiwog\\Documents\\projects\\application projects\\coffee_shop\\design\\icons\\back.png")); // NOI18N
        BackIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackIconMouseClicked(evt);
            }
        });

        ProductImage.setForeground(new java.awt.Color(255, 255, 255));
        ProductImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ProductImage.setText("<ProductImage>");
        ProductImage.setPreferredSize(new java.awt.Dimension(300, 300));

        ProductShowName.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        ProductShowName.setForeground(new java.awt.Color(255, 255, 255));
        ProductShowName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ProductShowName.setText("<ProductShowName>");

        QuantityIncrase.setIcon(new javax.swing.ImageIcon("C:\\Users\\kiwog\\Documents\\projects\\application projects\\coffee_shop\\design\\icons\\incrase.png")); // NOI18N
        QuantityIncrase.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                QuantityIncraseMouseClicked(evt);
            }
        });

        Quantitydecrase.setIcon(new javax.swing.ImageIcon("C:\\Users\\kiwog\\Documents\\projects\\application projects\\coffee_shop\\design\\icons\\decrase.png")); // NOI18N
        Quantitydecrase.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                QuantitydecraseMouseClicked(evt);
            }
        });

        ProductShowQuantity.setFont(new java.awt.Font("Ubuntu", 1, 20)); // NOI18N
        ProductShowQuantity.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ProductShowQuantity.setText("<P>");

        AddToCart.setIcon(new javax.swing.ImageIcon("C:\\Users\\kiwog\\Documents\\projects\\application projects\\coffee_shop\\design\\icons\\add to cart.png")); // NOI18N
        AddToCart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddToCartMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(QuantityIncrase)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ProductShowQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Quantitydecrase)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 432, Short.MAX_VALUE)
                .addComponent(AddToCart)
                .addGap(92, 92, 92))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(AddToCart)
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ProductShowQuantity)
                            .addComponent(Quantitydecrase)
                            .addComponent(QuantityIncrase))
                        .addGap(30, 30, 30))))
        );

        ProductShowPrice.setFont(new java.awt.Font("Ubuntu", 3, 20)); // NOI18N
        ProductShowPrice.setForeground(new java.awt.Color(255, 255, 255));
        ProductShowPrice.setText("<ProductShowPrice>");

        StockTitle.setFont(new java.awt.Font("Ubuntu Medium", 0, 18)); // NOI18N
        StockTitle.setForeground(new java.awt.Color(255, 255, 255));
        StockTitle.setText("Stock :");

        ProductShowStock.setFont(new java.awt.Font("Ubuntu Medium", 0, 18)); // NOI18N
        ProductShowStock.setForeground(new java.awt.Color(255, 255, 255));
        ProductShowStock.setText("<st>");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ProductImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(342, 342, 342))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ProductShowName, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(StockTitle)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ProductShowStock))
                            .addComponent(ProductShowPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(BackIcon))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(103, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(BackIcon)
                .addGap(8, 8, 8)
                .addComponent(ProductImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(ProductShowName)
                .addGap(18, 18, 18)
                .addComponent(ProductShowPrice)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StockTitle)
                    .addComponent(ProductShowStock))
                .addGap(28, 28, 28)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(138, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackIconMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);

        if (this.BackFormat.equals("normal")) {

            ProductPage productPage = new ProductPage();
            productPage.setVisible(true);
            productPage.pack();
            productPage.setLocationRelativeTo(null);
            productPage.setDefaultCloseOperation(ProductPage.EXIT_ON_CLOSE);

        } else if (this.BackFormat.equals("edit")) {

            CartPage cartPage = new CartPage();
            cartPage.setVisible(true);
            cartPage.pack();
            cartPage.setLocationRelativeTo(null);
            cartPage.setDefaultCloseOperation(CartPage.EXIT_ON_CLOSE);

        }
        
    }//GEN-LAST:event_BackIconMouseClicked

    private void QuantityIncraseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QuantityIncraseMouseClicked
        // TODO add your handling code here:
        if (this.QuantityProductDefault >= this.ProductStock) {
            
            this.QuantityProductDefault = this.ProductStock;
            this.ProductStockDefault = 0;
            
        } else {
            
            this.ProductStockDefault -= 1;
            this.QuantityProductDefault += 1;
        }
        
        ProductShowStock.setText(String.valueOf(this.ProductStockDefault));
        ProductShowQuantity.setText(String.valueOf(this.QuantityProductDefault));
    }//GEN-LAST:event_QuantityIncraseMouseClicked

    private void QuantitydecraseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QuantitydecraseMouseClicked
        // TODO add your handling code here:
        if (this.QuantityProductDefault <= this.MinimumOrder) {
            
            this.QuantityProductDefault = this.MinimumOrder;
            this.ProductStockDefault = this.ProductStock - this.MinimumOrder;
            
        } else {
            
            this.ProductStockDefault += 1;
            this.QuantityProductDefault -= 1;
        }
        
        ProductShowStock.setText(String.valueOf(this.ProductStockDefault));
        ProductShowQuantity.setText(String.valueOf(this.QuantityProductDefault));
    }//GEN-LAST:event_QuantitydecraseMouseClicked

    private void AddToCartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddToCartMouseClicked
        // TODO add your handling code here:
        
        System.out.println("-------- Pesanan Baru -------");
        System.out.println("Nama Barang    : " + this.ProductName);
        System.out.println("Banyak Barang  : " + String.valueOf(this.QuantityProductDefault));
        System.out.println("Harga Barang   : " + this.PriceParsing.PriceNumberToPriceStringFormat(this.ProductPrice));
        System.out.println("----------------------------");
        System.out.println("Total Harga    : " + this.PriceParsing.PriceNumberToPriceStringFormat(this.ProductPrice * this.QuantityProductDefault) + "\n");

        OrderRepository OrderRepo = new OrderRepository();
        boolean CreateOrder = OrderRepo.createOrder(
            new OrderModel(
                this.ProductName,
                this.ProductPrice, 
                this.QuantityProductDefault,
                this.ProductImageDetail
            )
        );

        if ( CreateOrder ) {

            System.out.println("data baru");
        } else {

            System.out.println("data gagal ditambahkan");
        }

    }//GEN-LAST:event_AddToCartMouseClicked

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ProductOrderPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ProductOrderPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ProductOrderPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ProductOrderPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ProductOrderPage().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddToCart;
    private javax.swing.JLabel BackIcon;
    private javax.swing.JLabel ProductImage;
    private javax.swing.JLabel ProductShowName;
    private javax.swing.JLabel ProductShowPrice;
    private javax.swing.JLabel ProductShowQuantity;
    private javax.swing.JLabel ProductShowStock;
    private javax.swing.JLabel QuantityIncrase;
    private javax.swing.JLabel Quantitydecrase;
    private javax.swing.JLabel StockTitle;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
